# Generated by Django 5.1.4 on 2024-12-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicId', models.IntegerField()),
                ('ChapterName', models.CharField(max_length=100)),
                ('ChapterDesc', models.CharField(max_length=500)),
            ],
        ),
    ]
