# Generated by Django 5.1.4 on 2024-12-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='TopicDesc',
            field=models.TextField(),
        ),
    ]
